version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - zzzaim
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@fortawesome/fontawesome-free"
    versions:
    - 5.15.2
  - dependency-name: mustache
    versions:
    - 4.1.0
  - dependency-name: bulma
    versions:
    - 0.9.1
  - dependency-name: lodash
    versions:
    - 4.17.20
